#---------------------------------------------------#
# Step 1: Install and Load Required Packages
#---------------------------------------------------#

# Use a conditional check to install packages if they are not already present.
if (!requireNamespace("terra", quietly = TRUE)) {
  install.packages("terra", dependencies = TRUE)
}

if (!requireNamespace("geodata", quietly = TRUE)) {
  install.packages("geodata", dependencies = TRUE)
}

# Load the packages
library(terra)
library(geodata)

#---------------------------------------------------#
# Step 2: Load Your Coordinates Data
#---------------------------------------------------#

# Read your tab-separated file called 'locations.txt'
# The 'header=TRUE' argument assumes the first row contains column names.
# The 'sep="\t"' argument specifies that tabs are used as separators.
locations <- read.csv("locations.txt", header = TRUE, sep = "\t")

# Convert the coordinates dataframe into a SpatVector object.
# The `geom` argument is used to specify the coordinate columns by name.
points_spatvector <- vect(locations, geom = c("Longitud", "Latitud"), crs = "EPSG:4326")

#---------------------------------------------------#
# Step 3: Download and Load WorldClim Bioclimatic Data
#---------------------------------------------------#

# Download the WorldClim v2.1 bioclimatic data (bio1-19) at a resolution of 30 arc-seconds (~1 km).
# The country code "REU" is used for Reunion Island.
# The files will be saved in a folder named 'wc2-1' within your working directory.
bioclim_data <- geodata::worldclim_country(country = "REU", var = "bio", res = 0.5, path = ".")

#---------------------------------------------------#
# Step 4: Extract Bioclimatic Values for Each Individual
#---------------------------------------------------#

# Extract the bioclimatic data from the raster layers using your coordinates.
# The `xy = TRUE` argument adds the coordinates of the raster cell to the output.
# The `cells = TRUE` argument adds the raster cell ID to the output.
extracted_data <- terra::extract(bioclim_data, points_spatvector, xy = TRUE, cells = TRUE)

#---------------------------------------------------#
# Step 5: Combine Data and Clean Up
#---------------------------------------------------#

# Combine the original locations data with the extracted bioclimatic data.
# The `!names(...) %in% ...` syntax correctly removes the `ID` and `cell` columns
# which are generated by the `extract` function. This prevents a column name conflict.
final_df <- cbind(locations, extracted_data[, !names(extracted_data) %in% c("ID", "cell")])

# Print the first few rows of the final combined dataframe to verify the result.
print("Combined data for RDA analysis:")
print(head(final_df))

# Save the final combined data to a CSV file for future use.
# `row.names = FALSE` prevents R from writing the row numbers as a column in the file.
write.csv(final_df, "individual_bioclim_data.csv", row.names = FALSE)
